### ISSUE TITLE
Feature Request - Details when mouse over a point of the graph

### ISSUE THREAD

**Issue by erwanlr** [parikls/mem_usage_ui#1]
Thank you for the UI, it has been very helpful (even though I am going crazy trying to improve the memory usage of my script, haha xD)

I have a feature request: to be able to have the details (time and memory) of a point when the mouse is over it on the graph

**Comment by parikls** [comment]
@erwanlr thanks for the feedback! i had such feature in one of the very first versions, but it was a bit laggy on my laptop due to a lot of points on the chart. I will double check this

**Comment by erwanlr** [comment]
If it was done in real time while the monitored process was running, yes it may be laggy. In my case, having this feature enabled when the process is finished is enough :)

**Comment by parikls** [comment]
@erwanlr implemented in 0.9 (`pip install mem_usage_ui==0.9`). After you stop snapshotting - tooltips will be visible

**Comment by erwanlr** [comment]
Great, could it also be visible when the process doesn't exist anymore/has been terminated please ?

**Comment by parikls** [comment]
@erwanlr you mean the tooltips are always visible? please refresh browser cache (ctrl+F5 or cmd+R for macos) and try again

**Comment by parikls** [comment]
@erwanlr regarding processes - what is the reason for such functionality request? How do you want to use this?

**Comment by erwanlr** [comment]
Yea, if I refresh they are gone, not an issue really ;D

Here is how I currently use this:

- I run a script via a command with some arguments in a terminal and monitor its memory usage, then I either wait for the script to finish, or kill it.
- Then, I modify the script where I think the memory usage could be improved and do the above again to see any noticeable changes.
- Repeat until satisfied or losing my sanity ;D

**Comment by parikls** [comment]
Have you tried to use a combination of `Filter processes` input + `refresh processes` button? 
For example you can write your script name in that filter input, and when process ends - just click `refresh processes` and you will get a new PID

**Comment by erwanlr** [comment]
Oh yea, that's what I do already :), otherwise it would be a nightmare haha ;P

**Comment by parikls** [comment]
i will think on some periodical updating

**Comment by parikls** [comment]
@erwanlr added process auto-refresh in `0.9.1`

**Comment by erwanlr** [comment]
Awesome, thanks!
