### ISSUE TITLE
Upgrade to psutil==5.8.0

### ISSUE THREAD

**Issue by loukad** [parikls/mem_usage_ui#13]
Cool tool!  Thank you for creating it.

Trying to run it on my new Macbook Air M1, however, I was getting Input/Output exceptions from `psutil`, which the library creators have resolved in 5.8.0.  Once I upgraded that dependency, everything worked like a charm.

**Comment by parikls** [comment]
@loukad thanks for reporting this! Fixed in `1.0.6`
